#!/usr/bin/env bash
# Keeps Claude attribution out of what cloud sessions publish. CLAUDE.md forbids
# it, but the cloud environment adds it on its own; see "No attribution" in
# docs/ENVIRONMENT-CLOUD.md. The local terminal adds none, so this does nothing there.
[ "$CLAUDE_CODE_REMOTE" = true ] || exit 0

input=$(cat)
case $(jq -r .hook_event_name <<<"$input") in
SessionStart)
  # The container commits as "Claude <noreply@anthropic.com>", and GitHub's
  # squash merge credits every commit author with a Co-authored-by trailer.
  git -C "$CLAUDE_PROJECT_DIR" config user.name 'Christian Rauh'
  git -C "$CLAUDE_PROJECT_DIR" config user.email 'chris@rauh.net'
  ;;
PreToolUse)
  # gh api appends a footer to every body it sends, so it may only read.
  # Only the gh api command itself, up to the next separator, so text that
  # merely mentions it (a commit message) and other commands' flags don't count.
  call=$(jq -r .tool_input.command <<<"$input" |
    grep -oE '(^|[;&|(]|&&|\|\|)[[:space:]]*gh api[^;&|]*')
  if grep -qE '[[:space:]](-f|-F|--field|--raw-field|--input)([[:space:]]|=|$)' <<<"$call" &&
    ! grep -qE '(-X|--method)[ =]?GET' <<<"$call"; then
    jq -n '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: "deny",
      permissionDecisionReason: "In the cloud, gh api appends a \"Generated by Claude Code\" footer to every body it sends. Post and edit with the GitHub MCP tools; use gh api only to read."}}'
  fi
  ;;
PostToolUse)
  # issue_write also updates; only a create gets the footer.
  [ "$(jq -r '.tool_input.method // "create"' <<<"$input")" = create ] || exit 0
  jq -n '{hookSpecificOutput: {hookEventName: "PostToolUse",
    additionalContext: "GitHub now has a \"Generated by Claude Code\" footer at the end of the body you just created; the cloud appends it. Re-send the same body with the matching update tool (update_pull_request, update_issue_comment, or issue_write with method update), then read it back with gh api to confirm the footer is gone. If no update tool exists for it, tell the user so they can edit it."}}'
  ;;
esac
