/**
 * Visual Regression Tests for Shakuhachi Platform
 *
 * These tests ensure that refactoring doesn't introduce visual regressions.
 * Baselines are stored in tests/visual/__screenshots__/ (auto-generated by Playwright)
 *
 * Coverage:
 *   - Landing page and Akatombo score page
 *   - Button components test page
 *   - Score renderer test examples (15 test cases × 2 themes)
 *   - Light and dark color schemes
 *   - Desktop (1280x780) and mobile (375x1450) viewports
 *
 * Usage:
 *   npm run test:visual              # Run visual regression tests
 *   npm run test:visual:update       # Update baseline screenshots
 *   npm run test:visual:report       # View HTML report with diffs
 */

import { test, expect, type Page } from '@playwright/test';

// Test configurations
const pages = [
  { name: 'landing', path: '/', hasWebComponent: false },
  { name: 'akatombo', path: '/score/akatombo', hasWebComponent: true },
  { name: 'buttons', path: '/test/buttons', hasWebComponent: false },
];

const colorSchemes = ['light', 'dark'] as const;

const viewports = [
  { name: 'desktop', width: 1280, height: 780 },
  { name: 'mobile', width: 375, height: 1450 },
];

async function waitForScoreRendered(page: Page) {
  await page.waitForFunction(() => {
    const c = document.querySelector('shakuhachi-score');
    return c?.shadowRoot?.querySelector('svg') !== null;
  });
}

test.describe('Visual Regression', () => {
  test.beforeEach(async ({ page }) => {
    // Set consistent timezone and locale for reproducible rendering
    await page.addInitScript(() => {
      // Force consistent date/time
      Date.now = () => 1609459200000; // 2021-01-01 00:00:00 UTC
    });
  });

  // Generate tests for each combination
  for (const pageConfig of pages) {
    for (const colorScheme of colorSchemes) {
      for (const viewport of viewports) {
        const testName = `${pageConfig.name} - ${colorScheme} - ${viewport.name}`;
        const screenshotName = `${pageConfig.name}-${colorScheme}-${viewport.name}.png`;

        test(testName, async ({ page }) => {
          // Set viewport
          await page.setViewportSize({
            width: viewport.width,
            height: viewport.height,
          });

          // Set color scheme
          await page.emulateMedia({ colorScheme });

          // Navigate to page
          await page.goto(pageConfig.path);

          // Wait for rendering to complete
          if (pageConfig.hasWebComponent) {
            await waitForScoreRendered(page);
          }

          // Take screenshot and compare to baseline
          await expect(page).toHaveScreenshot(screenshotName, {
            fullPage: false,
          });
        });
      }
    }
  }

  // Shakuhachi-score web component test page - single full-page screenshot
  // (Page already includes both light/dark themes side-by-side)
  test('shakuhachi-score - full page', async ({ page }) => {
    // Set viewport wide enough to fit the 1000px fixed-width page
    await page.setViewportSize({
      width: 1280,
      height: 2000, // Tall enough to capture all 3 examples
    });

    // Navigate to page
    await page.goto('/test/shakuhachi-score.html');

    // Wait for rendering to complete
    await waitForScoreRendered(page);

    // Take full-page screenshot
    await expect(page).toHaveScreenshot('shakuhachi-score-full-page.png', {
      fullPage: true,
    });
  });
});
