/**
 * Visual Regression Tests for Shakuhachi Score Renderer
 *
 * These tests ensure that refactoring doesn't introduce visual regressions.
 * Baselines are stored in tests/visual/__screenshots__/ (auto-generated by Playwright)
 *
 * Usage:
 *   npm run test:visual              # Run visual regression tests
 *   npm run test:visual:update       # Update baseline screenshots
 *   npm run test:visual:report       # View HTML report with diffs
 */

import { test, expect } from '@playwright/test';

test.describe('Visual Regression - Akatombo Score', () => {
  // Configure viewport for all tests
  test.use({
    viewport: { width: 1280, height: 720 },
  });

  test.beforeEach(async ({ page }) => {
    // Set consistent timezone and locale for reproducible rendering
    await page.addInitScript(() => {
      // Force consistent date/time
      Date.now = () => 1609459200000; // 2021-01-01 00:00:00 UTC
    });
  });

  test('renders full Akatombo score (default view)', async ({ page }) => {
    // Navigate to the score page
    await page.goto('/');

    // Wait for rendering to complete
    await page.waitForTimeout(2000);

    // Take full page screenshot and compare to baseline
    await expect(page).toHaveScreenshot('akatombo-full-page.png', {
      fullPage: true,
    });
  });

  test('renders full score with viewport (default view)', async ({ page }) => {
    // Navigate to the score page
    await page.goto('/');

    // Wait for rendering to complete
    await page.waitForTimeout(2000);

    // Take viewport screenshot (what user sees without scrolling)
    await expect(page).toHaveScreenshot('akatombo-viewport.png', {
      fullPage: false,
    });
  });

  test('renders with debug labels enabled', async ({ page }) => {
    // Navigate with debug query parameter
    await page.goto('/?debug=true');

    // Wait for rendering to complete
    await page.waitForTimeout(2000);

    // Take full page screenshot with debug labels
    await expect(page).toHaveScreenshot('akatombo-debug-full.png', {
      fullPage: true,
    });
  });

  test('renders debug mode in viewport', async ({ page }) => {
    // Navigate with debug query parameter
    await page.goto('/?debug=true');

    // Wait for rendering to complete
    await page.waitForTimeout(2000);

    // Take viewport screenshot with debug labels
    await expect(page).toHaveScreenshot('akatombo-debug-viewport.png', {
      fullPage: false,
    });
  });

  // Additional test: Verify SVG is rendered (sanity check)
  test('SVG element is present and rendered', async ({ page }) => {
    await page.goto('/');
    await page.waitForTimeout(2000);

    // Check that SVG exists
    const svg = await page.locator('svg');
    await expect(svg).toBeVisible();

    // Check that SVG has content (notes rendered)
    const svgContent = await page.locator('svg text').first();
    await expect(svgContent).toBeVisible();
  });

  // Additional test: Verify score title is displayed
  test('displays score title and metadata', async ({ page }) => {
    await page.goto('/');
    await page.waitForTimeout(2000);

    // Check title is displayed
    const title = await page.locator('h1#score-title');
    await expect(title).toContainText('Akatombo');
  });
});
