/**
 * Visual Regression Tests for Shakuhachi Platform
 *
 * These tests ensure that refactoring doesn't introduce visual regressions.
 * Baselines are stored in tests/visual/__screenshots__/ (auto-generated by Playwright)
 *
 * Coverage:
 *   - Landing page and Akatombo score page
 *   - Light and dark color schemes
 *   - Desktop (1280x720) and mobile (375x667) viewports
 *
 * Usage:
 *   npm run test:visual              # Run visual regression tests
 *   npm run test:visual:update       # Update baseline screenshots
 *   npm run test:visual:report       # View HTML report with diffs
 */

import { test, expect } from '@playwright/test';

// Test configurations
const pages = [
  { name: 'landing', path: '/' },
  { name: 'akatombo', path: '/score/akatombo' },
];

const colorSchemes = ['light', 'dark'] as const;

const viewports = [
  { name: 'desktop', width: 1280, height: 720 },
  { name: 'mobile', width: 375, height: 667 },
];

test.describe('Visual Regression', () => {
  test.beforeEach(async ({ page }) => {
    // Set consistent timezone and locale for reproducible rendering
    await page.addInitScript(() => {
      // Force consistent date/time
      Date.now = () => 1609459200000; // 2021-01-01 00:00:00 UTC
    });
  });

  // Generate tests for each combination
  for (const pageConfig of pages) {
    for (const colorScheme of colorSchemes) {
      for (const viewport of viewports) {
        const testName = `${pageConfig.name} - ${colorScheme} - ${viewport.name}`;
        const screenshotName = `${pageConfig.name}-${colorScheme}-${viewport.name}.png`;

        test(testName, async ({ page }) => {
          // Set viewport
          await page.setViewportSize({
            width: viewport.width,
            height: viewport.height,
          });

          // Set color scheme
          await page.emulateMedia({ colorScheme });

          // Navigate to page
          await page.goto(pageConfig.path);

          // Wait for rendering to complete
          await page.waitForTimeout(1000);

          // Take screenshot and compare to baseline
          await expect(page).toHaveScreenshot(screenshotName, {
            fullPage: false,
          });
        });
      }
    }
  }
});
